import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/layout/nav";
import { ProductProvider } from "@/context/ProductContext";
import Footer from "@/components/layout/footer";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
});
export const metadata = {
  title: "Exclosive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={poppins.className}>
     
      <body
        
      >
         <Navbar/>
       <ProductProvider>{children}</ProductProvider>
       <Footer/>
      </body>
    </html>
  );
}
